### PR TITLE
New hotkey: H - Toggle Video Control Bar

### PR DESCRIPTION
**Pull request by primeinc**
Was very annoyed that the control bar wouldn't go away sometimes without refreshing the page. Was using your extension for the spacebar pausing an figured I could contribute.

I made the hotkey work anywhere regardless of focus so I don't have to click and pause the video by accident. I'd be happy to move it to focus only if you prefer. 

Awesome quick and simple extension! Thanks

### CODE REVIEW

**Comment by avi12** [comment]
That's a good idea!
Though, if hide the controls when pressing H, it'd also make sense to hide them when going fullscreen
What do you think?

**Comment by primeinc** [comment]
Well that was my issue to begin with. I haven't tried to troubleshoot it at all (it could be a different extension or something particular with my computer) but when on a skillshare video if I go fullscreen and don't move the mouse the control bar goes away on its own, however it seems like if I move the mouse and click on anything to seek or change the volume the control bar refuses to go away unless I refresh the page.

That has nothing to do with your question though, haha. To answer it, I think that hiding the control bar automatically without some kind of toast / popup notification that you have to press H or exit fullscreen to get it to come back would impact the user experience for the uninformed.

**Comment by avi12** [comment]
You're right
On a second thought regarding the user experience, I'm considering maybe it'd be better to fix the "control bar not hiding" behavior
Basically, making the player's behavior as close as possible to the YouTube player

**Comment by avi12** [comment]
I'm working on a better feature: instead of pressing H, the control bar will automatically show/hide based on the fullscreen state and the mouse movement

**Comment by avi12** [comment]
I finished working on this feature: #5 
Though I won't officially make a release package (in [Releases](https://github.com/avi12/skillshare-player-control/releases)) just yet, as I'm using this extension to test [web-ext-deploy](../../web-ext-deploy)

**Pull request closed without merging**
